development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bitcoin-bank_prod
  pool: 5
  username: rails
  password: rails

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bitcoin-bank_test
  pool: 5
  username: rails
  password: rails
