development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bitcoin-bank_development
  pool: 5
  username: rails
  password: rails
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bitcoin-bank_test
  pool: 5
  username: rails
  password: rails
  socket: /var/run/mysqld/mysqld.sock
